"""Test Migration

Revision ID: 54c1a6543ef6
Revises: f56c8ec1083a
Create Date: 2025-02-09 09:53:18.432017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c1a6543ef6'
down_revision: Union[str, None] = 'f56c8ec1083a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(), nullable=True))
    op.drop_column('users', 'auth_tokne')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_tokne', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###
